### ISSUE TITLE
Failed to instantiate due to Unknown Provider

### ISSUE THREAD

**Issue by computersarecool** [gtramontina/stripe-angular#7]
I get this error `Failed to instantiate module myApp due to:
Error: [$injector:unpr] Unknown provider: Stripe`

When I try to include the library as follows:

`angular.module('myApp', ['stripe]).config(function (Stripe) {
    Stripe.setPublishableKey('my_key');
})`

Both uppercase and lowercase fail.

This was installed with bower and I see `stripe-angular` in my bower_components folder.

**Comment by mahaveer-bitcot** [comment]
I face the same problem

**Comment by gtramontina** [comment]
Stripe is not a factory or service, there's no `Stripe` provider. The `Stripe` instance on which we call `setPublishableKey` is the one provided by the stripe library that we bring in with `<script type="text/javascript" src="https://js.stripe.com/v2/"></script>`.

Here's how you should be using it (like on the [readme](https://github.com/gtramontina/stripe-angular#setup)):
```js
angular.module('myApp', ['stripe'])
.config(function() {
  Stripe.setPublishableKey('your-publishable-key');
});
```

Please note that the function passed to `.config` does not take any parameters.

Let me know if that solves your problem so that I can close this issue.

**Comment by jonathanasquier** [comment]
This works well before build, but won't once the code is obfuscated.

**Comment by growthclick** [comment]
I ran into an instantiation issue but fixed it by adding these two lines to my index.html: 
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script type="text/javascript" src="lib/stripe-angular/stripe-angular.js"></script>

The second line isn't mentioned in the readme but I assume it's required for Angular to recognize the stripe module. (I'm still learning Angular).

**Comment by mikeLspohn** [comment]
Yes the Readme just needs updated to reflect the extra step.

**Comment by gtramontina** [comment]
Oh yes... Thanks for pointing that out @growthclick (and @mikeLspohn for the gentle reminder 😊). I'm adding that like to the readme.

@jonathanasquier where you able to spot where the breakage happens? The module already takes care of using the array approach to inject the dependencies...

@computersarecool and @mahaveer-bitcot have you ever overcome the issue you where facing?

**Comment by jonathanasquier** [comment]
The module works well obfuscated I believe the mistake was on my side. Sorry for the late response!

**Comment by gtramontina** [comment]
Awesome.. I'm closing this one, then. Thanks!
